---
Name: search_simple_smart
After:
  - 'framework/*'
  - 'cms/*'
Before:
  - 'app/*'
---
Page:
  extensions:
    - Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineMakeSearchable
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineSiteConfigExtension
SilverStripe\ErrorPage\ErrorPage:
  search_engine_exclude_from_index: true
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineContentControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - searchengine/css/SearchEngineCMS.css
  extra_requirements_javascript:
    - searchengine/javascript/CMS.js
